<b> Goal </b> \
This tutorial will mainly focus on how to represent matrices in python, and how to do some of the basic matrix manipulations.

In [2]:
from PIL import Image  #This imports the Python Image Library (PIL).
import math   #Module for extra math functions
import numpy as np   #The main module that allows us to create and manipulate matrices

get_ipython().magic('matplotlib inline')   #this is included to help make our plots 
import matplotlib.pyplot as plt            #this is the main plotting module

In [4]:
#declaring matrices with numpy
#2x2 matrix.
#the first brackets (i.e. [1,2]) constitute the first row of the matrix, 
#and similarly for the second brackets ([3,4] second row)
#Be sure to have brackets around the whole thing ... [[1,2],[3,4]] in this example
A_1 = np.array([[1,2],[3,4]]) 
print("A_1 = \n", A_1)
#column vectors (i.e. an nx1 matrix)
v_1 = np.array([[10],[7]])  #a 2x1 column matrix
print("v_1 = \n", v_1)

A_1 = 
 [[1 2]
 [3 4]]
v_1 = 
 [[10]
 [ 7]]


In [5]:
#To get the shape of a matrix (i.e. the number of rows and columns ... (r,c)) use .shape :
print("The shape of A_1 is ", A_1.shape)

The shape of A_1 is  (2, 2)


In [6]:
#we can also make a few simple matrices without specifying each matrix entry:
Zeros = np.zeros( (2,3) )  #this create a 2x3 matrix whose entries are all zero
print("Zeros = \n", Zeros)
Ones = np.ones(v_1.shape)  #this creates a matix of all ones with the same shape as v_1
print("Ones = \n", Ones)
ID = np.eye(4)   #this creates an identity matrix of size 4x4 (it must be square) https://www.mathbootcamps.com/the-identity-matrix-and-its-properties/
print("Identity Matrix = \n", ID)

Zeros = 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones = 
 [[1.]
 [1.]]
Identity Matrix = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<b> Exercise: </b> 
Create a 2x4 matrix whose entries are the first 8 prime numbers. Show that it has the correct shape.

In [7]:
#Solution
#Create a 2x4 matrix whose entries are the first 8 prime numbers. Show that it has the correct shape.
P_1 = np.array([[2,3],[5,7],[11,13],[17,19]])
print("P_1 = \n", P_1)
print("The shape of A_1 is ", P_1.shape)

P_1 = 
 [[ 2  3]
 [ 5  7]
 [11 13]
 [17 19]]
The shape of A_1 is  (4, 2)


<b> Simple matrix manipulations (addition & multiplication) </b> 

Recall that to add or subtract matrices, you can only do this for matrices of the same shape


In [8]:
#You just subtract or add the matrices with "-" or "+"
A_2 = np.array([[4,3],[2,1]])
A_3 = A_2 - A_1               
print("A_2 - A_1 = \n", A_3)

A_2 - A_1 = 
 [[ 3  1]
 [-1 -3]]


In [11]:
#To multiply matrices you need to use np.dot(Matrix1, Matrix2)
#using "*" is NOT the same!! This would multipy element-wise
A_4 = np.dot(A_1,A_2)
print("A_1 x A_2 = \n", A_4)

#You need to make sure that for AxB, the number of columns in A is equal to the number of rows in B
A_5 = np.dot(A_1,v_1)
print("A_1 x v_1 = \n", A_5)


A_1 x A_2 = 
 [[ 8  5]
 [20 13]]
A_1 x v_1 = 
 [[24]
 [58]]


<b> Exercise: </b> 
Please compute the product of A_1, v_1, if you encounter an error, please try to explain 
what is the cause of that error. 

In [ ]:
#Solution
#notice that we can compute np.dot(A_1,v_1) since A_1.shape = (2,2) and v_1.shape = (2,1), but
#np.dot(v_1,A_1) would give an error for miss-aligned shapes
A_6 = np.dot(v_1,A_1)
print("A_1 x v_1 = \n", A_6)